### ISSUE TITLE
Generating loads of commands dynamically from config files

### ISSUE THREAD

**Issue by enxebre** [Cilex/Cilex#55] opened 2014-09-03 07:23 UTC
I created this library for generating loads of commands dynamically from config files https://github.com/enxebre/CliGenerator. might be interesting interesting add an "addCommands" function for the applications class.

**Comment by Seldaek** [comment] 2016-11-20 13:52
Duplicate of #27 kinda so closing

**Closed by Seldaek** 2016-11-20 13:52 UTC
